TRUNCATE TABLE [dbo].[dotNetEndOfLife]

INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'.NetCoreApp,Version=v5.0', N'2022-05-08', NULL, N'.Net 5.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 10', N'2021-12-24', NULL, N'@angular/core 10', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 11', N'2022-05-11', NULL, N'@angular/core 11', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 12', N'2022-11-12', NULL, N'@angular/core 12', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 13', N'2023-05-04', NULL, N'@angular/core 13', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 14', N'2023-11-18', NULL, N'@angular/core 14', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 15', N'2024-05-18', NULL, N'@angular/core 15', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 16', N'2024-11-08', NULL, N'@angular/core 16', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 2', N'2020-12-24', NULL, N'@angular/core 2', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 3', N'2020-12-24', NULL, N'@angular/core 3', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 4', N'2020-12-24', NULL, N'@angular/core 4', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 5', N'2020-12-24', NULL, N'@angular/core 5', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 6', N'2020-12-24', NULL, N'@angular/core 6', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 7', N'2020-12-24', NULL, N'@angular/core 7', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 8', N'2020-12-24', NULL, N'@angular/core 8', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'@angular/core 9', N'2020-12-24', NULL, N'@angular/core 9', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net4.6.2', N'2027-01-12', NULL, N'.Net Framework 4.6.2', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net45', N'2016-01-12', NULL, N'.Net Framework 4.5', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net451', N'2016-01-12', NULL, N'.Net Framework 4.5.1', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net452', N'2022-04-26', NULL, N'.Net Framework 4.5.2', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net46', N'2022-04-26', NULL, N'.Net Framework 4.6', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net461', N'2022-04-26', NULL, N'.Net Framework 4.6.1', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net462', N'2027-01-12', NULL, N'.Net Framework 4.6.2', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net47', NULL, NULL, N'.Net Framework 4.7', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net471', NULL, NULL, N'.Net Framework 4.7.1', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net472', NULL, NULL, N'.Net Framework 4.7.2', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net48', NULL, NULL, N'.Net Framework 4.8', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net481', NULL, NULL, N'.Net Framework 4.8.1', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net5.0', N'2022-05-08', NULL, N'.Net 5.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net50', N'2022-05-08', NULL, N'.Net 5.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net6', N'2024-11-12', NULL, N'.Net 6.0', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net6.0', N'2024-11-12', NULL, N'.Net 6.0', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net6.0-windows', N'2024-11-12', NULL, N'.Net 6.0', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net7.0', N'2024-05-14', NULL, N'.Net 7.0', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'net8.0', N'2027-11-14', NULL, N'.Net 8.0', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netcoreapp1.0', N'2019-06-27', NULL, N'.Net Core 1.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netcoreapp1.1', N'2019-06-27', NULL, N'.Net Core 1.1', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netcoreapp2.0', N'2018-10-01', NULL, N'.Net Core 2.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netcoreapp2.1', N'2021-08-21', NULL, N'.Net Core 2.1', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netcoreapp2.2', N'2019-12-23', NULL, N'.Net Core 2.2', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netcoreapp3.0', N'2020-03-03', NULL, N'.Net Core 3.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netcoreapp3.1', N'2022-12-03', NULL, N'.Net Core 3.1', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netcoreapp5.0', N'2022-05-08', NULL, N'.Net 5.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netstandard1.0', NULL, NULL, N'.Net Standard 1.0', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netstandard1.3', NULL, NULL, N'.Net Standard 1.3', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netstandard1.4', NULL, NULL, N'.Net Standard 1.4', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netstandard1.5', NULL, NULL, N'.Net Standard 1.5', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netstandard2.0', NULL, NULL, N'.Net Standard 2.0', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'netstandard2.1', NULL, NULL, N'.Net Standard 2.1', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v1.0', N'2013-10-08', NULL, N'.Net Framework 1.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v1.1', N'2015-07-14', NULL, N'.Net Framework 1.1', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v2.0', N'2011-07-12', NULL, N'.Net Framework 2.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v3.0', N'2011-07-12', NULL, N'.Net Framework 3.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v3.5', N'2029-01-09', NULL, N'.Net Framework 3.5', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.0', N'2016-01-12', NULL, N'.Net Framework 4.0', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.5', N'2016-01-12', NULL, N'.Net Framework 4.5', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.5.1', N'2016-01-12', NULL, N'.Net Framework 4.5.1', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.5.2', N'2022-04-26', NULL, N'.Net Framework 4.5.2', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.6', N'2022-04-26', NULL, N'.Net Framework 4.6', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.6.1', N'2022-04-26', NULL, N'.Net Framework 4.6.1', 0, 0)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.6.2', N'2027-01-12', NULL, N'.Net Framework 4.6.2', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.7', NULL, NULL, N'.Net Framework 4.7', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.7.1', NULL, NULL, N'.Net Framework 4.7.1', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.7.2', NULL, NULL, N'.Net Framework 4.7.2', 0, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.8', NULL, NULL, N'.Net Framework 4.8', 1, 1)
INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display], [IsTargetVersion], [IsSupportedVersion]) VALUES (N'v4.8.1', NULL, NULL, N'.Net Framework 4.8.1', 1, 1)
