DECLARE @count03 INT
SELECT @count03 = COUNT(*) FROM dbo.dotNetEndOfLife

IF @count03 = 0
BEGIN
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net45', N'2016-01-12', NULL, N'.Net Framework 4.5')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net451', N'2016-01-12', NULL, N'.Net Framework 4.5.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net452', N'2020-01-14', NULL, N'.Net Framework 4.5.2')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net46', N'2020-01-14', NULL, N'.Net Framework 4.6')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net461', N'2020-01-14', NULL, N'.Net Framework 4.6.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net462', N'2022-01-11', NULL, N'.Net Framework 4.6.2')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net4.6.2', N'2022-01-11', NULL, N'.Net Framework 4.6.2')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net47', N'2020-01-14', NULL, N'.Net Framework 4.7')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net471', N'2022-01-11', NULL, N'.Net Framework 4.7.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net472', N'2024-01-09', NULL, N'.Net Framework 4.7.2')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net48', N'2024-01-09', NULL, N'.Net Framework 4.8')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netcoreapp1.0', N'2019-06-27', NULL, N'.Net Core 1.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netcoreapp1.1', N'2019-06-27', NULL, N'.Net Core 1.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netcoreapp2.0', N'2018-10-01', NULL, N'.Net Core 2.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netcoreapp2.1', N'2021-08-21', NULL, N'.Net Core 2.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netcoreapp2.2', N'2019-12-23', NULL, N'.Net Core 2.2')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netcoreapp3.0', N'2020-03-03', NULL, N'.Net Core 3.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netcoreapp3.1', N'2022-12-03', NULL, N'.Net Core 3.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v1.0', N'2013-10-08', NULL, N'.Net Framework 1.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v1.1', N'2015-07-14', NULL, N'.Net Framework 1.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v2.0', N'2011-07-12', NULL, N'.Net Framework 2.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v3.0', N'2011-07-12', NULL, N'.Net Framework 3.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v3.5', N'2023-10-10', N'2025-01-14', N'.Net Framework 3.5')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.0', N'2016-01-12', NULL, N'.Net Framework 4.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.5', N'2016-01-12', NULL, N'.Net Framework 4.5')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.5.1', N'2016-01-12', NULL, N'.Net Framework 4.5.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.5.2', N'2020-01-14', NULL, N'.Net Framework 4.5.2')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.6', N'2020-01-14', NULL, N'.Net Framework 4.6')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.6.1', N'2020-01-14', NULL, N'.Net Framework 4.6.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.6.2', N'2022-01-11', NULL, N'.Net Framework 4.6.2')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.7', N'2020-01-14', NULL, N'.Net Framework 4.7')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.7.1', N'2022-01-11', NULL, N'.Net Framework 4.7.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.7.2', N'2024-01-09', NULL, N'.Net Framework 4.7.2')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.8', N'2024-01-09', NULL, N'.Net Framework 4.8')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'v4.8.1', N'2024-01-09', NULL, N'.Net Framework 4.8.1')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net5.0', N'2022-05-08', NULL, N'.Net 5.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'net50', N'2022-05-08', NULL, N'.Net 5.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netcoreapp5.0', N'2022-05-08', NULL, N'.Net 5.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'.NetCoreApp,Version=v5.0', N'2022-05-08', NULL, N'.Net 5.0')

	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netstandard1.0', NULL, NULL, N'.Net Standard 1.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netstandard1.3', NULL, NULL, N'.Net Standard 1.3')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netstandard1.4', NULL, NULL, N'.Net Standard 1.4')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netstandard1.5', NULL, NULL, N'.Net Standard 1.5')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netstandard2.0', NULL, NULL, N'.Net Standard 2.0')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'netstandard2.1', NULL, NULL, N'.Net Standard 2.1')

	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 2', N'2020-12-24', NULL, N'@angular/core 2')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 3', N'2020-12-24', NULL, N'@angular/core 3')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 4', N'2020-12-24', NULL, N'@angular/core 4')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 5', N'2020-12-24', NULL, N'@angular/core 5')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 6', N'2020-12-24', NULL, N'@angular/core 6')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 7', N'2020-12-24', NULL, N'@angular/core 7')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 8', N'2020-12-24', NULL, N'@angular/core 8')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 9', N'2020-12-24', NULL, N'@angular/core 9')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 10', N'2021-12-24', NULL, N'@angular/core 10')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 11', N'2022-05-11', NULL, N'@angular/core 11')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 12', N'2022-11-12', NULL, N'@angular/core 12')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 13', N'2023-05-04', NULL, N'@angular/core 13')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 14', N'2023-11-18', NULL, N'@angular/core 14')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 15', N'2024-05-18', NULL, N'@angular/core 15')
	INSERT INTO [dbo].[dotNetEndOfLife] ([Version], [EOL], [ExtendedEOL], [Display]) VALUES (N'@angular/core 16', N'2024-11-08', NULL, N'@angular/core 16')	

END