CREATE TABLE [dbo].[Reports]
(
    [Timestamp] DATE NOT NULL,
    [Organization] NVARCHAR(50) NOT NULL, 
    [Project] NVARCHAR(MAX) NOT NULL,
    [ProjectId] NVARCHAR(50) NOT NULL,
    [ProjectDescription] NVARCHAR(MAX) NOT NULL,
    [ProjectUrl] NVARCHAR(MAX) NOT NULL,
    [Repository] NVARCHAR(MAX) NOT NULL,
    [RepositoryId] NVARCHAR(50) NOT NULL,
    [RepositoryDefaultBranch] NVARCHAR(MAX) NOT NULL,
    [RepositoryUrl] NVARCHAR(MAX) NOT NULL,
    [FileType] NVARCHAR(50) NOT NULL,
    [FileId] NVARCHAR(50) NOT NULL,
    [FilePath] NVARCHAR(MAX) NOT NULL,
    [FileUrl] NVARCHAR(MAX) NOT NULL,
    [AzureFunction] NVARCHAR(50) NULL,
    [IsAzureFunction] BIT NOT NULL,
    [FrameworkVersion] NVARCHAR(50) NULL,
    [IsEol] BIT NOT NULL,
    [EolDate] DATE NULL,
    [Eol3Months] BIT NOT NULL,
    [Eol6Months] BIT NOT NULL,
    [Eol9Months] BIT NOT NULL,
    [Eol12Months] BIT NOT NULL,
    [SupportedFramework] BIT NOT NULL,
    [TargetFramework] BIT NULL,
    [FileReference] NVARCHAR(MAX) NULL,
    [UrlReference] NVARCHAR(MAX) NULL,
    [PackageType] NVARCHAR(50) NULL,
    [PackageName] NVARCHAR(MAX) NULL,
    [PackageVersion] NVARCHAR(MAX) NULL
)
